### ISSUE TITLE
Ability to customize shape after creating new

### ISSUE THREAD

**Issue by LaMbA3** [maoschanz/drawing#461] opened 2021-12-09 12:37 UTC
## Requested feature

It would be very nice if after drawing shape you could move and change it. This would probably require some kind of hand tool to move and select shape that you want to edit. Also it would be nice if you could duplicate shape. 

## Use case

I currently an looking for software that is very simple, just for adding some lines and rectangles to screenshots. This software looks very good and is easy to use, but when drawing some shape you need to be very precise because you cant edit it after. I think it would be huge imrovement if you could.

**Comment by maoschanz** [comment] 2021-12-09 13:17
Duplicate of the pinned issue #123

**Closed by maoschanz** 2021-12-09 13:17 UTC
Labels: feature request
