### ISSUE TITLE
Please remove polemic screenshot from appdata

### ISSUE THREAD

**Issue by yodatak** [maoschanz/drawing#205] opened 2020-03-09 14:14 UTC
Can you remove the fucking zemour image we don't need racist guy to advertise apps

**Comment by maoschanz** [comment] 2020-03-09 14:37
duplicate of issue #159, appdata screenshots change when the UI changes.

The image ridiculing the fascist clown will probably stay until the release of the version 0.6.1

**Closed** 2020-09-15 09:14 UTC
Labels: duplicate, invalid/out of scope, packaging
