### ISSUE TITLE
Drawing horizontal straight line

### ISSUE THREAD

**Issue by alex-tw-lam** [maoschanz/drawing#462] opened 2021-12-14 02:58 UTC
## Requested feature
To draw a horizontal straight line by holding the shift key. 

### Possible drawbacks
no

### Possible alternatives
Snapping the line to a horizontal angle would work just as well. 

## Use case
Draw a line under some text in an image. It would be nice if the highlight tool could draw straight lines.

**Comment by maoschanz** [comment] 2021-12-14 08:17
Duplicate of both #46 and #369

The orientation locking is already here since the version 0.8.2 as a regular option of the "line" tool

**Closed by maoschanz** 2021-12-14 08:17 UTC
Labels: feature request
