### ISSUE TITLE
Drawing app is very laggy on decent hardware

### ISSUE THREAD

**Issue by Netherquark** [maoschanz/drawing#425] opened 2021-10-02 13:07 UTC
## Use case

I just use drawing to doodle/note down formulae while im studying and its surprisingly laggy for that use case. I use an AMD 2200G based system with 8GB of ram, utilising the integrated graphics, which is more than enough for a simple Paint-equivalent I'd reckon. I think the problem is probably related to hardware acceleration, or rather, a lack thereof.
I'm finding that as I use the pen/cil utility, the drawing lags behind and when I undo/redo, it lags for a solid 5 seconds or so before becoming functional again.

## Suggested solution

I think working on hardware acceleration would help a lot.

**Comment by maoschanz** [comment] 2021-10-02 13:31
>as I use the pen/cil utility, the drawing lags behind

this is a bug correlated to the size of the canvas, and it will be improved with version 1.0.0

It could probably benefit from hardware acceleration but i've no idea if it's feasible before switching to GTK4

>when I undo/redo, it lags for a solid 5 seconds or so before becoming functional again. 

this one is trickier because it's caused by the architecture of the history. Basically, an "undo" recomputes everything you did (except the undone operation) since the last time you saved the picture. If you don't save often, or use tools that require more complex computation (blurring, selection, etc.), it may take a lot of time

The app could "remember" more frequently the entire picture so there would be less to compute, but then it would use more RAM

**Comment by Netherquark** [comment] 2021-10-02 13:34
excited for V1 then!

I think for the latter, it might be a good idea to allow that in settings. Up to you though. It'll be a pretty bit of coding on your end.

**Comment by maoschanz** [comment] 2021-10-16 00:22
(closed because it's a duplicate of #200 and #168)

**Closed by maoschanz** 2021-10-16 00:22 UTC
Labels: enhancement
