### ISSUE TITLE
Option to edit inserted text

### ISSUE THREAD

**Issue by MintMain21** [maoschanz/drawing#526] opened 2022-05-25 21:14 UTC
## Use case

The "Insert Text" feature is nice as-is, but it's impossible to edit text once it's been properly inserted, which makes it impossible to fix typos. I suppose this puts more importance on making sure the text is right before inserting it, but nevertheless, the option to edit text would be most welcome.

## Suggested solution

Rename "Insert Text" to "Text", and include options to edit text already inserted into the image. Ideally, this would be done by right-clicking on text and selecting "edit", similar to in programs like Libre-Office. 

### Possible drawbacks

It could make things confusing if the feature isn't logically placed in the current workflow, but I trust that it will fit organically in the program given the proper care.

**Comment by maoschanz** [comment] 2022-05-25 21:49
duplicate of #123

**Closed by maoschanz** 2022-05-25 21:49 UTC
Labels: enhancement

**Comment by maoschanz** [comment] 2022-05-25 21:50
although that issue 123 doesn't mention clicking on pixels from the canvas to edit specific operations, because it's likely impossible in a raster image editor
