### ISSUE TITLE
"Text" tool couldn't insert Chinese.

### ISSUE THREAD

**Issue by isweibin** [maoschanz/drawing#251] opened 2020-08-12 10:05 UTC
Hello, seems that couldn't insert Chinese by "Text" tool.

## System

- Device (desktop computer/tablet/phone/...): laptop computer
- OS: LinuxMint 20
- Desktop environment: xfce
- Package format (flatpak, native package, snap?): installed by apt tool
- App version: 0.4.13

**Comment by maoschanz** [comment] 2020-08-12 10:08
(duplicate of #180 )

**Closed** 2020-08-16 21:23 UTC
Labels: duplicate, enhancement, tools
