### ISSUE TITLE
Missing save/export dialog

### ISSUE THREAD

**Issue by coresh** [maoschanz/drawing#247] opened 2020-08-05 20:39 UTC
# Where is Path / Location of:

1. Saved drawing's
2. Saved drawing's as svg file

The reason:

For further editing by gimp / photoshop / illustrator

Thank you

**Comment by maoschanz** [comment] 2020-08-05 23:51
I don't understand the issue: when you export/save as, there's a dialog where *you* decide the location 

Also, Drawing can't export as SVG. If you name a file with such an extension from Drawing, it'll be saved as a PNG and most other apps will say it's an invalid file.

**Comment by coresh** [comment] 2020-08-06 03:20
Re: ```I don't understand the issue: when you export/save as, there's a dialog where you decide the location```:
Got it.

But, in my case -> no dialog window.
Only the silent black icon like ```download file```.

Any default ```/path/to/saved/files``` ?

**Comment by maoschanz** [comment] 2020-08-06 08:00
You haven't clicked on the "Save" or "Export" confirmation button in the dialog, so the file is not saved at all.

This is a bug, please provide these information asked by the bug report template:

- Device (desktop computer/tablet/phone/...):
- OS:
- Desktop environment:
- Package format (flatpak, native package, snap?):
- App version:

Then, you should start the app from a terminal, reproduce the bug, and show me the error that will be written in the terminal

**Comment by maoschanz** [comment] 2020-08-26 07:46
I will guess that the information you don't want to tell are *"desktop computer/elementaryOS/Pantheon/Flatpak/0.4.13"* and thus i'll close your issue as a duplicate of #60 

If this is not the case, just answer to provide the info asked in the first place

**Closed by maoschanz** 2020-08-26 07:46 UTC
Labels: bug, need infos, question
