### ISSUE TITLE
Let the object resize after it finishes till unselected.

### ISSUE THREAD

**Issue by avil25** [maoschanz/drawing#224] opened 2020-05-17 10:09 UTC
## Use case
Many times I need to align two objects in certain patterns, and most of the time I can not do it one go. If I am using other software like ms paints or pinta they let me resize the object right after drawing and align it correctly but in drawing, I need to delete the shape and draw again or use selection to move it. this happens mostly when I try to align circle with another shape.

## Suggested solution
 I like the approach of ms paints they let me move objects if I hold the mouse in between the shape and resize the shape with the corner of the shape. I can play with the object as long as I want and when I click on click outside of the shape it gets unselected and fixed.

### Possible drawbacks
Drawing lets me draw non-symmetrical shapes with polygon don't know how it will work with them.

### Possible alternatives
If I can resize the object I selected then also I can archive the same although it will be a two-step process.

**Comment by maoschanz** [comment] 2020-05-17 13:20
duplicate of #123 

i like the feature, but i've always viscerally abhorred the way modern MS Paint implements it, so i have to find a more usable way to do it, and it will take time

**Closed by maoschanz** 2020-05-17 13:20 UTC
Labels: enhancement
