### ISSUE TITLE
Automatic resizing of canvas when you insert an image, which is larger than canvas

### ISSUE THREAD

**Issue by pervoj** [maoschanz/drawing#307] opened 2020-11-28 18:31 UTC
Now, when you paste image from clipboard, which is larger than canvas, application crops it to size of canvas. It would be better, when the application ask you, if you want to crop the image, or resize canvas, just like for example Pinta has.

**Comment by maoschanz** [comment] 2020-11-28 19:34
this behavior is here by design: users should be able to set a canvas size, and then import an image, and there is not a single good reason to break the chosen size when they import something. It's imported as the selection, so if it's too big you can already scale it or crop it. Or cut it to resize the canvas and paste it later if you really don't want to scale down anything

i close it because it's a duplicate of #184 #222 , where the best suggested improvement in my opinion is to dim the part of the selection that would be cropped, to make it more visible

**Closed** 2020-11-28 19:56 UTC
Labels: feature request
