### ISSUE TITLE
Resize canvas with click-and-drag tools like in MS Paint

### ISSUE THREAD

**Issue by mwmcewan** [maoschanz/drawing#378] opened 2021-05-14 20:17 UTC
## Requested feature

In the corners of an MS Paint canvas, there are small white boxes you can use to resize the canvas to a size you need. I think it would be super helpful if Drawing had this functionality too.

### Possible drawbacks

I don't believe so. It does not have to be utilized by those who do not prefer it.

### Possible alternatives

I don't think there are any alternatives as easy as this,

## Use case

In MS Paint, I often use this functionality to help clean up screenshots.

**Comment by maoschanz** [comment] 2021-05-14 21:07
This is a duplicate of issues #85 #212 and probably a few other ones

Not listing the drawbacks doesn't make them disappear.

- What size should those elements be, so we don't interact with them by accident, but can still use them from a touchscreen? 
- Should people be able to scroll further than the size of their image to access those elements? In all directions? Or only 3 of them like with most versions of MS Paint? Anyway that would mean rewriting 60% of the app to render this blank area
- How would you scale the image without being highly inconsistent? With MS Paint, those boxes crop/expand, and scaling the image is done through a weird dialog window with numerical inputs. I'll not regress from live-previewed intuitive scaling to a crappy dialog.

So sorry, that's too complex to do, and with zero benefit since the crop tool now works quite fine.

**Closed by maoschanz** 2021-05-14 21:07 UTC
Labels: duplicate, feature request, wontfix
