### ISSUE TITLE
Color Picker does not work

### ISSUE THREAD

**Issue by ThisIsTheLongestUsernameinTheWorldDude** [maoschanz/drawing#229] opened 2020-06-01 17:43 UTC
Selecting the color picker and clicking on an image does not change the current color.

To reproduce

1. Open image in Drawing
2. Select Color Picker
3. Left Click somewhere in image
4. Current color does not change to what you clicked

- Device: desktop
- OS: Linux Mint 19.3
- Desktop environment: Cinnamon
- Package format: Apt preinstalled in mint
- App version: 0.4.7

**Comment by maoschanz** [comment] 2020-06-01 18:34
Duplicate of #119, fixed 6 months ago. If you're using such an old version of the app, please check if your problem has already been reported before opening a new issue

**Closed by maoschanz** 2020-06-01 18:34 UTC
Labels: bug, duplicate
