### ISSUE TITLE
Stucks in open \ save dialogue

### ISSUE THREAD

**Issue by emcampinline** [maoschanz/drawing#22] opened 2019-03-29 03:14 UTC
## Description
The app stucks in the open\save dialogue, and does not respond to mouse or keyboard

## Steps to reproduce the bug:
1. Open the dialogue window by clicking Open, Save, Export etc. 
2. At the bottom right corner click the file type selector.

## System
- Device: Desktop 32-bit
- OS:  Fedora 29
- Desktop: Gnome 3.30.2
- Package format: Flatpak
- App version: 0.2.0

## Additional context
Awesome app, thanks!

**Comment by maoschanz** [comment] 2019-03-29 09:32
This dialog isn't provided by the app, but by the system, and i can't reproduce the bug on Debian Sid, so it looks like a GTK bug specific to Fedora 29

**Comment by maoschanz** [comment] 2019-07-31 18:00
Since i've no new info and i can't reproduce it, i'm closing this issue

**Closed by maoschanz** 2019-07-31 18:00 UTC
Labels: bug, need infos
