### ISSUE TITLE
Support fonts with full unicode encoding

### ISSUE THREAD

**Issue by suiwenfeng** [maoschanz/drawing#180] opened 2020-02-05 09:47 UTC
## Problem

looks insert chinese text is not support yet.

**Comment by maoschanz** [comment] 2020-02-05 10:29
i think it's an issue with fonts

**Comment by suiwenfeng** [comment] 2020-02-06 02:22
i write a mirco test using pycairo. and get block while insert unicode text. let me try other fonts.

```
import cairo
def main():
    ims = cairo.ImageSurface(cairo.FORMAT_ARGB32, 390, 60)
    cr = cairo.Context(ims)
    
    cr.set_source_rgb(0, 0, 0)
    cr.select_font_face("Sans", cairo.FONT_SLANT_NORMAL, cairo.FONT_WEIGHT_NORMAL)
    cr.set_font_size(40)
    
    cr.move_to(10, 50)
    cr.show_text("中文测试")
    
    ims.write_to_png("image.png")
    
if __name__ == "__main__":
    main()
```

**Comment by maoschanz** [comment] 2020-02-06 03:11
your issue is actually a duplicate of #58, which will be fixed when i'll implement that  https://www.cairographics.org/cookbook/pycairo_pango/

**Comment by suiwenfeng** [comment] 2020-02-06 06:52
That`s great.

**Comment by maoschanz** [comment] 2020-08-16 15:38
it was easier to fix than what i expected

![Capture d’écran de 2020-08-16 17-35-12](https://user-images.githubusercontent.com/19996113/90338020-ed019f00-dfe6-11ea-9f82-27abf6ade2f4.png)

it'll be distributed with the version 0.6

**Closed** 2020-08-16 21:23 UTC
Labels: enhancement, tools
