### ISSUE TITLE
Undo becomes slow when an image contains many lines

### ISSUE THREAD

**Issue by Exalm** [maoschanz/drawing#282] opened 2020-10-07 15:19 UTC
## Description

See the recording, compare with redo.

![Peek 2020-10-07 20-14](https://user-images.githubusercontent.com/1510457/95350709-e7834f80-08d9-11eb-9ecf-f15f4d3fbb0d.gif)

I was told it took like 7 seconds on their machine.

**Comment by Exalm** [comment] 2020-10-07 15:20
Oh cool, black screen. Looks like recordings are still borked on F33.

**Comment by Exalm** [comment] 2020-10-07 15:21
GitHub doesn't let me attach a webm, so:

[Screencast from 07-10-20 20:13:12.zip](https://github.com/maoschanz/drawing/files/5341767/Screencast.from.07-10-20.20.13.12.zip)

**Comment by maoschanz** [comment] 2020-10-07 15:35
Undoing rebuilds the image from the last time you saved (= it draws hundreds of lines, since you haven't saved yet). Redoing just redraws the undone line.

it's easier to reproduce with selection (define, move, copy, paste, import, ...) or transform tools (crop, scale, filters, ...), since they're far heavier to execute than simple lines

closed because it's the duplicate of #200

**Closed by maoschanz** 2020-10-07 15:35 UTC
Labels: bug

**Comment by Exalm** [comment] 2020-10-07 15:41
Ah, my bad :)
